### ISSUE TITLE
Failed assertion: line 732 pos 7: '_ticker != null': AnimationController.stop() called after AnimationController.dispose()

### ISSUE THREAD

**Issue by obrunsmann** [leonzone/loading#16]
Hey!

I am using this package within the following BLoC implementation:

```
Center(
  child: state is LogCreateSubmitting
      ? Loading()
      : RaisedButton(
          child: Text('Submit'),
          onPressed: () {
            context.bloc<LogCreateBloc>().add(CreateFormSubmitted(
                  _startDate,
                  _endDate,
                  _summaryController.text,
                  _noteController.text,
                ));
          },
        ),
),
```

As soon as the state changes await from _LogCreateSubmitting_ and the Loading gets unmounted the exception throws.

I wrapped your Library withing a small statelss widget so that I do not have to repeat my loading type all over the application:

```
import 'package:flutter/material.dart';
import 'package:loading/indicator/ball_pulse_indicator.dart';
import 'package:loading/loading.dart' as LoadingSdk;

class Loading extends StatelessWidget {
  const Loading({Key key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return LoadingSdk.Loading(
      color: Theme.of(context).primaryColor,
      indicator: BallPulseIndicator(),
    );
  }
}

```

Log:

```
[VERBOSE-2:ui_dart_state.cc(157)] Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 732 pos 7: '_ticker != null': AnimationController.stop() called after AnimationController.dispose()
AnimationController methods should not be used after calling dispose.
#0      _AssertionError._doThrowNew  (dart:core-patch/errors_patch.dart:42:39)
#1      _AssertionError._throwNew  (dart:core-patch/errors_patch.dart:38:5)
#2      AnimationController.stop 
package:flutter/…/animation/animation_controller.dart:732
#3      AnimationController.repeat 
package:flutter/…/animation/animation_controller.dart:628
#4      BallPulseIndicator.startAnim  (package:loading/indicator/ball_pulse_indicator.dart:48:16)
#5      BallPulseIndicator.startAnims.<anonymous closure>  (package:loading/indicator/ball_pulse_indicator.dart:55:9)
#6      new Future.delayed.<anonymous closure>  (dart:async/future.dart:316:39)
#7      _rootRun  (dart:async/zone.dart:1122:38)
#8      _CustomZon<…>
```

**Comment by 410063005** [comment]
I've encountered the same question。 This is my workaround: create a fixed verson Indicator 

https://gist.github.com/410063005/937a9a464a58f5bcc1c0d9b4ad1f1b31

Hope it helps

**Comment by 410063005** [comment]
It was fixed in this commit https://github.com/leonzone/loading/commit/8f5a63fff48d371ff4de96865861c5c24f58f7b5

But maybe we need a new release

**Comment by smasinde** [comment]
If anyone wants to use the fix while you wait for the official release, put it like this in your pubspec:

>      loading:
>         git:
>           url: git://github.com/leonzone/loading.git
>           path: loading
>           ref: 8f5a63f

**Comment by Dreamersoul** [comment]
hello,
when will be released officially?
thank you

**Comment by silkyland** [comment]
Release this please.....

**Comment by zenkog** [comment]
Got the same issue, when will this be released ?

**Comment by m0veax** [comment]
Can we support you to release that commit?
