### ISSUE TITLE
Visibility error

### ISSUE THREAD

**Issue by kaminarifox** [leonzone/loading#5]
Got error when use Loading Widget inside Visibility and changing visible flag. Same if use just ternary operator

```
E/flutter ( 3591): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: 'package:flutter/src/animation/animation_controller.dart': Failed assertion: line 671 pos 7: '_ticker != null': AnimationController.animateWith() called after AnimationController.dispose()
E/flutter ( 3591): AnimationController methods should not be used after calling dispose.
E/flutter ( 3591): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:40:39)
E/flutter ( 3591): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:36:5)
E/flutter ( 3591): #2      AnimationController.animateWith (package:flutter/src/animation/animation_controller.dart:671:7)
E/flutter ( 3591): #3      AnimationController.repeat (package:flutter/src/animation/animation_controller.dart:626:12)
E/flutter ( 3591): #4      BallSpinFadeLoaderIndicator.startAnims.<anonymous closure> (package:loading/indicator/ball_spin_fade_loader_indicator.dart:49:24)
E/flutter ( 3591): #5      new Future.delayed.<anonymous closure> (dart:async/future.dart:316:39)
E/flutter ( 3591): #6      _rootRun (dart:async/zone.dart:1120:38)
E/flutter ( 3591): #7      _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 3591): #8      _CustomZone.runGuarded (dart:async/zone.dart:923:7)
E/flutter ( 3591): #9      _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
E/flutter ( 3591): #10     _rootRun (dart:async/zone.dart:1124:13)
E/flutter ( 3591): #11     _CustomZone.run (dart:async/zone.dart:1021:19)
E/flutter ( 3591): #12     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:947:23)
E/flutter ( 3591): #13     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:21:15)
E/flutter ( 3591): #14     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:382:19)
E/flutter ( 3591): #15     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:416:5)
E/flutter ( 3591): #16     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)
E/flutter ( 3591): 
```

**Comment by Dorshitrit** [comment]
Hey, 
I have the same issue, 
happened after setState

**Comment by rupert2133** [comment]
try to add below code before setState
```
if(mounted){
  return;
}
// you setState here
```
